server:
  port: 8082
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
    username: papalaity
  zipkin:
    baseUrl: http://localhost:9411
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka